-- CREATE TABLE theologyforchildren_plans (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     day TEXT NOT NULL,
--     title INTEGER REFERENCES theologyforchildren_books(id),
--     verses INTEGER [] REFERENCES theologyforchildren_verses(id)
-- );

CREATE TABLE theologyforchildren_plans (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    day TEXT NOT NULL,
    title INTEGER REFERENCES theologyforchildren_books(id),
    verses INTEGER [],
    quiztitles INTEGER REFERENCES theologyforchildren_quiztitles(id)
);