CREATE TABLE theologyforchildren_quizes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    qname TEXT NOT NULL,
    question TEXT NOT NULL,
    answers TEXT[],
    correctanswer TEXT NOT NULL,
    useranswer TEXT NULL,
    qtconnect INTEGER REFERENCES theologyforchildren_quiztitles(id)
);