CREATE TABLE theologyforchildren_quizes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    qname TEXT NOT NULL,
    content TEXT NOT NULL,
    answer TEXT NOT NULL,
    user_id TEXT,
    qtconnect INTEGER REFERENCES theologyforchildren_quiztitles(id)
);