INSERT INTO theologyforchildren_contents (word, content)
VALUES
  ('Servant', 'A servant tends to his master.'),
  ('Apostle', 'Jesus made people apostles through His grace-gift so that they can help His church love God and love others.'),
  ('Faith', 'The faith that Paul is talking about is the growing faith of someone who trust Jesus as their Lord and Savior. Paul connects the “faith of the elect” with his grace-gift of being an Apostle.'),
  ('Truth', 'Truth in this context represents the Gospel. The Gospel states, “People are sinners. Jesus died on the cross for our sins. On the third day, He rose from the grave so that we may have life in Him. If we turn from our sins, believe that Jesus died and rose from the grave, and confess Jesus as Lord. We will be saved forever!”'),
  ('Eternal Life', 'God promises His children forever life when they trust Him as Lord and Savior. This life has no end and cannot be taken away or it wouldn’t be forever life.'),
  ('Preaching', 'The word “Preaching” is talking about the Gospel message. See “Truth”'),
  ('Savior', 'Jesus is the Savior for the world. He gave His life for you so that you can be saved. This is one reason He is called Savior.'),
  ('Elders', 'Another name for an Elder is a Preacher. God places elders in charge of His local churches in order to take care of His people by putting himself last and the rest of God’s children first.'),
  ('Reproach', 'God’s wants His elders to be blameless. In other words, an elder should stay out of trouble.'),
  ('One Wife', 'An elder-quality man serves his wife, works through problems, and puts her first. He knows that his wife is a priceless gift that he will never abandon.'),
  ('Arrogant', 'An arrogant person focuses on himself. He wants others to think that he is great. But an elder focuses on serving others. He wants others to know that Jesus is great.'),
  ('Quick-Tempered', 'The anger of man does not produce the righteousness of God. An elder is quick to listen, slow to speak, and slow to anger.'),
  ('Self-Controlled', 'An elder has control of himself and his desires. This includes how he thinks, speaks, and acts.'),
  ('Sound Doctrine', 'Sound doctrine means “healthy instructions.” God wants us to follow His words so that we can be spiritual well.'),
  ('Insubordinate', 'Insubordinate means disobedient. A person, who is insubordinate, disobeys God’s healthy instructions, and this person is spiritually sick.'),
  ('Empty Talkers', 'Empty talk is for an empty heart. But a heart filled with Christ overflows with Jesus’ Gospel and His healthy instructions.'),
  ('Deceivers', 'A deceiver misleads people. This is the opposite of an elder-quality man who leads people by serving them so that they know Christ more.'),
  ('Shameful Gain', 'Moths and rust destroy shameful gain and thieves break-in and steal it. Shameful gain could be money or attention. You can’t serve God and money. The attention of man is quickly fading.'),
  ('Gluttons', 'The Cretans did not tell the truth, loved evil, and served themselves. Glutton typically refers to a love for food that leads a big belly.'),
  ('Pure', 'Pure means innocent. Jesus makes us pure by washing us clean from our sins.'),
  ('Disobedient', 'The people that Paul spoke of were disobedient to God. They didn’t do what God said, which shows that they lied when they said “they know God.”'),
  ('Quarrels', 'Paul encourages the church to stop fighting. It is difficult to love when you are fighting.');